swagger: '2.0'
info:
    title: chat-ai
    description: chat-ai API Gateway with a Google Cloud Functions backend
    version: 0.0.1
schemes:
    - https
produces:
    - application/json
securityDefinitions:
    api_key_header:
        type: apiKey
        name: x-api-key
        in: header
paths:
    /planning:
        post:
            summary: planning API
            operationId: planning
            security:
                - api_key_header: []
            x-google-backend:
                address: https://asia-northeast1-radiant-voyage-325608.cloudfunctions.net/chatai
            parameters:
                - in: header
                  name: puroduct
                  description: target product
                  required: true
                  type: string
            responses:
                '200':
                    description: A successful response
                    schema:
                        type: string
