[tool.poetry]
name = "slack-sub-bot"
version = "0.1.0"
description = ""
authors = ["bulldra <bulldra@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.3"
beautifulsoup4 = "^4.12.0"
functions-framework = "^3.4.0"
google-cloud-logging = "^3.8.0"
google-cloud = "^0.34.0"
openai = "^1.3.4"
requests = "^2.31.0"
slack-sdk = "^3.23.0"
tiktoken = "^0.5.1"
types-requests = "^2.31.0"
types-beautifulsoup4 = "^4.12.0"
pytest = "^7.4.3"
youtube-transcript-api="^0.6.1"
feedparser = "^6.0.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
