export type AgentCategory = 'input' | 'judgment' | 'processing' | 'output' | 'utility';

export interface AgentMeta {
  name: string;
  description: string;
  category: AgentCategory;
  color: string;
  defaultArguments: Record<string, unknown>;
  contextInputs: string[];
  contextOutputs: string[];
}

export const agentRegistry: Record<string, AgentMeta> = {
  UrlClassifier: {
    name: 'UrlClassifier',
    description: 'URL種別を判定して分岐',
    category: 'judgment',
    color: '#FF6F00',
    defaultArguments: {},
    contextInputs: [],
    contextOutputs: [],
  },
  FunctionCalling: {
    name: 'FunctionCalling',
    description: 'LLMで意図を判定して分岐',
    category: 'judgment',
    color: '#6A1B9A',
    defaultArguments: {},
    contextInputs: [],
    contextOutputs: [],
  },
  ContentTypeRouter: {
    name: 'ContentTypeRouter',
    description: 'コンテンツ種別で分岐',
    category: 'judgment',
    color: '#00838F',
    defaultArguments: {},
    contextInputs: [],
    contextOutputs: [],
  },
  AgentGPT: {
    name: 'GPT',
    description: 'ChatGPTに会話を委譲',
    category: 'processing',
    color: '#4CAF50',
    defaultArguments: {},
    contextInputs: [],
    contextOutputs: [],
  },
  AgentSummarize: {
    name: 'Summarize',
    description: 'コンテンツを要約',
    category: 'processing',
    color: '#2196F3',
    defaultArguments: {},
    contextInputs: ['scraped_site'],
    contextOutputs: [],
  },
  AgentIdea: {
    name: 'Idea',
    description: 'アイディアを生成',
    category: 'processing',
    color: '#FF9800',
    defaultArguments: {},
    contextInputs: [],
    contextOutputs: [],
  },
  AgentRecommend: {
    name: 'Recommend',
    description: 'おすすめ記事を提案',
    category: 'processing',
    color: '#9C27B0',
    defaultArguments: {},
    contextInputs: [],
    contextOutputs: [],
  },
  AgentSlackMail: {
    name: 'SlackMail',
    description: 'メール処理',
    category: 'utility',
    color: '#607D8B',
    defaultArguments: {},
    contextInputs: [],
    contextOutputs: [],
  },
  AgentDelete: {
    name: 'Delete',
    description: 'メッセージ削除',
    category: 'utility',
    color: '#F44336',
    defaultArguments: {},
    contextInputs: [],
    contextOutputs: [],
  },
  AgentText: {
    name: 'Text',
    description: 'テキスト応答',
    category: 'output',
    color: '#795548',
    defaultArguments: {},
    contextInputs: [],
    contextOutputs: [],
  },
  AgentYoutube: {
    name: 'Youtube',
    description: 'YouTube動画を要約',
    category: 'input',
    color: '#FF0000',
    defaultArguments: {},
    contextInputs: [],
    contextOutputs: [],
  },
  AgentSearch: {
    name: 'Search',
    description: '検索実行',
    category: 'input',
    color: '#00BCD4',
    defaultArguments: {},
    contextInputs: [],
    contextOutputs: [],
  },
  AgentNotification: {
    name: 'Notification',
    description: 'Slack通知送信',
    category: 'output',
    color: '#E91E63',
    defaultArguments: {},
    contextInputs: [],
    contextOutputs: [],
  },
  AgentSlackHistory: {
    name: 'SlackHistory',
    description: 'Slack履歴取得',
    category: 'input',
    color: '#3F51B5',
    defaultArguments: {},
    contextInputs: [],
    contextOutputs: [],
  },
  AgentFeedDigest: {
    name: 'FeedDigest',
    description: 'フィードダイジェスト生成',
    category: 'processing',
    color: '#8BC34A',
    defaultArguments: {},
    contextInputs: ['x_posts', 'feed_messages', 'picked_quotes'],
    contextOutputs: ['feed_content'],
  },
  AgentFeedCollect: {
    name: 'FeedCollect',
    description: 'フィード収集',
    category: 'input',
    color: '#CDDC39',
    defaultArguments: {},
    contextInputs: [],
    contextOutputs: ['feed_messages'],
  },
  AgentX: {
    name: 'X',
    description: 'X(Twitter)ポスト分析',
    category: 'input',
    color: '#000000',
    defaultArguments: {},
    contextInputs: [],
    contextOutputs: [],
  },
  AgentXPost: {
    name: 'XPost',
    description: 'Xポスト取得',
    category: 'input',
    color: '#1DA1F2',
    defaultArguments: { pick_count: 20, fetch_files: 5 },
    contextInputs: [],
    contextOutputs: ['x_posts'],
  },
  AgentScrape: {
    name: 'Scrape',
    description: 'Webスクレイピング',
    category: 'input',
    color: '#FF5722',
    defaultArguments: {},
    contextInputs: [],
    contextOutputs: ['scraped_site'],
  },
  AgentQuotePicker: {
    name: 'QuotePicker',
    description: 'ビジネス名言をランダム抽出',
    category: 'utility',
    color: '#78909C',
    defaultArguments: { pick_count: 5 },
    contextInputs: [],
    contextOutputs: ['picked_quotes'],
  },
};
