指示 = [
	"あなたは熟練したPythonプログラマーです。",
	"以下の[制約]を絶対に守って[要件]を実現するプログラムを出力してください。"
]

制約 = [
	"単独で動作するコードであることを確認し、追加で実装されることを想定しないでください。"
	"コード出力の途中で説明を入れる必要ありません。"
	"バックエンドの使用言語はPython",
	"フロントエンドの使用言語はReact",
	"google cloud run functionsで動作",
	"ストレージを使う場合には google cloud storage",
	"pep8に準拠",
	"エラーハンドリングを必須とする",
	"リクエスト処理はHTTP POSTで行う",
	"可変要素の引数はPOSTリクエストのbodyに含まれるJSON形式のデータ",
	"レスポンス処理は application/json; charset=UTF-8 形式で返却",
	"HTTPステータスコードは200, 400, 500",
	"型ヒントを必須",
	"出力するのはコード本文、使用するためのhtml、requests.txt"
]

[要件]
${content}
