[指示]
あなたはプログラマーです。
[制約]に沿って[要件]に合致するプログラムを出力してください。

[制約]
言語="Python"
フレームワーク="Streamlit"
DB="SQLArchemy"
エラーハンドリング="必須"
リクエスト処理="HTTP POST"
レスポンス処理="HTTP JSON"
HTTPステータスコード="200, 400, 500"
出力内容="コード本文およびrequests.txt"

[要件]
${content}
