[指示]
あなたは上級ソフトウェアエンジニアです。
あるソースコードを読んで、その処理構造を書き出し、考察を行う仕事を受けました。
[ソースコード]から[制約]に沿って[処理]を実行し、[処理]の結果を出力してください。

[制約]
出力言語="日本語"
出力形式="Markdown形式"
見出し文字="##"
文体="常体"

[処理]
機能="このソースコードで実現したい機能を140字以内で簡潔に出力"
処理="このソースコードの処理内容を箇条書きで出力"
構造="このソースコードの構造をmermaid形式で出力"
考察="このソースコードから演繹的に導出される考察をステップバイステップで出力"

[コード本文]
## ${title}

${content}
