["指示"]
prompt="""
先ほどのサマリーと、サマリーと合わせて読むと理解が深まる関連記事を選んで、
そのタイトルとリンクを教えてください。
選定する際は、単なるキーワード一致だけでなく、
内容の関連性や補完性を考慮してください。

さらに、サマリーとレコメンド記事同士を掛け合わせて共通点を抜き出した上で
先ほどのサマリーを起点に創発的な事業企画やブログ記事をステップバイステップで考えて提案。
あくまで最初のサマリーを起点にしたアイディアであり、関連記事の内容は補完的に使ってください。

適切な記事が見つからない場合は、「関連するおすすめ記事は見つかりませんでした。」とだけ出力してください。
"""

output_format="""
## \\# 関連記事

- [記事タイトル1](リンク1)
    - 説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける 
    - 説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける 
- [記事タイトル2](リンク2)
    - 説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける 
    - 説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける 
- [記事タイトル3](リンク3)

## \\# 事業や記事の企画

最初のサマリーを起点にした企画をステップバイステップで考えて提案。
"""

"要望" = [
	"キャッチーなタイトルをつける。",
	"キャッチーな見出しをつける。",
	"ブログ記事としての主張を明確にする。",
	"共通点を抜き出して仮説を出して。",
	"水平思考で話を広げて。",
	"想定される疑問や反論を繰り返して。",
	"重要な示唆や発言を\"\"引用形式で出力。",
	"データや事実を示す場合は、出典を明らかにして。",
	"必要に応じて名言やアフォリズムを引用して。",
	"突飛な意見も恐れずに入れて。",
	"思わずシェアしたくなるような魅力的な記事にしてください。"
]

["制約"]
"出力言語"="日本語"
"出力形式"="Markdown形式（コードブロックは使用しない）"
"見出し文字"="##"
"文体"="常体"
"箇条書き"="構造化インデントは4スペース、数字箇条書きは使用せず空改行を入れない"

["処理対象"]
related_messages="""
${related_messages}
"""

