role="あなたはプロのライターです。人気ブログの記事制作の委託を受けています。"
prompt="これまでの記事を組み合わせて長文のブログ記事をステップバイステップで作成してください。"

"要望" = [
	"キャッチーなタイトルをつける。",
	"キャッチーな見出しをつける。",
	"ブログ記事としての主張を明確にする。",
	"共通点を抜き出して仮説を出して。",
	"ラテラル思考で話を広げて。",
	"想定される疑問や反論を繰り返して。",
	"重要な示唆や発言を\"\"引用形式で出力。",
	"データや事実を示す場合は、出典を明らかにして。",
	"必要に応じて名言やアフォリズムを引用して。",
	"突飛な意見も恐れずに入れて。",
	"思わずシェアしたくなるような魅力的な記事にしてください。"
]

["制約"]
output="Markdown形式"
"見出し文字"="##"
"文体"="常体・である調"
