["指示"]
keyword="${keyword}"
prompt="これまでの内容を組み合わせてリサーチ結果をまとめるブログ記事をステップバイステップで作成してください。"

"要望" = [
	"キャッチなータイトルや見出しをつける。",
	"記事の構成を明確にする。",
	"記事の構成に合わせて各セクションを埋める。",
	"Wiredを参考にした書き方。",
	"重要な示唆や発言を\"\"引用形式で出力。",
	"データや事実を示す場合は、出典を明らかにして。",
	"必要に応じて名言やアフォリズムを引用して。",
	"今後の展望を演繹的に出力。",
	"最後に記事内にあったURLを参考文献として列挙。",
]

"構成" = [
	"キャッチ",
	"序論",
	"問い",
	"仮説",
	"示唆",
	"結論",
	"参考文献",
]

["制約"]
output="Markdown形式"
"見出し文字"="##"
"文体"="常体・である調"
