["指示"]
prompt="""
あるニュースレターを読んで、その内容を要約し、考察を行い、関連情報を抽出する仕事を受けました。
[記事本文]から[制約]に沿って[処理]を実行し、[output_format]の形式で[処理]の結果を出力してください。
"""
output_format="""
## \\# 要約

また、米国の不法移民政策強化や関税政策の影響は、ECサイトの価格上昇や株式市場の動向にも波及しており、  
[ECプラットフォームA、日本で一部商品の価格を大幅上昇](https://example.com/news/001) や  
[米株指数、続伸し100ドル高　関税交渉進展への期待で](https://example.com/news/002) が示すように、  
経済面での不確実性が高まっている。  

国内では、総合商社CがAI資格を管理職昇格要件にするなど、AI技術の重要性が増していることが注目される  
（[総合商社C、ITパスポート管理職の昇格要件に　全社員必修へ](https://example.com/news/003)）。  
これは、企業がデジタルトランスフォーメーションを加速させ、競争力を維持・強化しようとする動きの一環である。  
また、AI新興企業Dの収益過大計上疑惑  
（[AI新興企業D、株価急落](https://example.com/news/004)）は、  
技術革新と企業統治の課題を浮き彫りにしている。

## \\# リンク

- [記事タイトル1](リンク1のURLに括弧をつける)
    - 説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける 
    - 説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける 
- [記事タイトル2](リンク2のURLに括弧をつける)
    - 説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける 
    - 説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける 
- [記事タイトル3](リンク3のURLに括弧をつける)
"""

["制約"]
"出力言語"="日本語"
"出力形式"="Markdown形式（コードブロックは使用しない）"
"見出し文字"="##"
"文体"="常体"
"箇条書き"="構造化インデントは4スペース、数字箇条書きは使用せず空改行を入れない"

["処理"]

"要約"="""
メール内の文章やリンクを要約して短時間でもポイントを抑えた読みやすい文章として1000文字程度で出力。
リンクの内容に言及する場合には文章中にリンクをつける
subjectになっているキーワードを重要な可能性が高いため優先的に言及
共通点が見出せる内容については同じ文章内でまとめて出力
"""
"リンク"="""
htmlからタイトルとリンクを抽出
ニュース、記事、話題、商品、書名等のリンクをMECEで出力
抽出したリンクのタイトルとURL文字列は改変せず、特にexample.com のようなドメインにはしない
リンクは `[タイトル](URL)` の Markdown 形式で必ず括弧を閉じる
リンクの付近に関連する解説や価格などがある場合は4文字スペースのインデントをして - の箇条書きで付与
数字箇条書きは使用せず、- を利用した階層的な箇条書きとする
配信停止、情報配信サービス設定変更、プライバシーポリシー、質問フォーム、お問い合わせなど定型的なリンクは不要
"""

["メール"]
subject = "## ${subject}"
content = """
${content}
"""

