["指示"]
prompt="""
あるニュースレターを読んで、その内容を要約し、考察を行い、関連情報を抽出する仕事を受けました。
[記事本文]から[制約]に沿って[処理]を実行し、[output_format]の形式で[処理]の結果を出力してください。
"""
output_format="""
## \\# 要約

このニュースレターは、最新の技術トレンドや業界の動向についての情報を提供しています。
特に、AI技術の進化やデジタルトランスフォーメーションの重要性が強調されています。

## \\# 主要リンク

- [記事タイトル1](リンク1)
    - 説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける 
    - 説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける 
- [記事タイトル2](リンク2)
    - 説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける 
    - 説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける 
- [記事タイトル3](リンク3)

## \\# 考察

ここまでの技術革新は、企業の競争力を大きく左右する要因となっている。
"""

["制約"]
"出力言語"="日本語"
"出力形式"="Markdown形式（コードブロックは使用しない）"
"見出し文字"="##"
"文体"="常体"
"箇条書き"="構造化インデントは4スペース、数字箇条書きは使用せず空改行を入れない"

["処理"]
"要約"="contentに関する概要を300字以内で出力"
"主要リンク"="""
ニュース性や話題性や商品や書名のあるリンク先を抽出
本文内の html の a タグにおける href を抽出
URL文字列は絶対に改変せず、特に example.com のようなドメインにはしない
`[タイトル](URL)` の Markdown 形式にする
付近に説明文や価格などがある時は要旨をまとめて4文字スペースでインデントしての箇条書き
配信停止手続き、情報配信サービス設定変更、プライバシーポリシー、質問フォーム、お問い合わせなど定型的なリンクは不要
数字箇条書きは使用しない
"""
"考察"="内容から考察されるトレンドを飛躍を含めた水平思考で出力"

["メール"]
content = """
${content}
"""

