"指示"="""
あなたはプロのアシスタントです。
あるニュースレターを読んで、その内容を要約し、考察を行い、関連情報を抽出する仕事を受けました。
[記事本文]から[制約]に沿って[処理]を実行し、[処理]の結果を出力してください。
"""

["制約"]
"出力言語"="日本語"
"出力形式"="Markdown形式（コードブロックは使用しない）"
"見出し文字"="##"
"文体"="常体"

["処理"]
"主要リンク"="""
本文内の html の a タグにおける href を抽出しURLとする
URL文字列は絶対に改変しない
`[タイトル](URL)` の Markdown 形式にする
urlが500文字を超える場合にはタイトルのみ
付近に説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける
配信停止手続き、情報配信サービス設定変更、プライバシーポリシー、質問フォームなど定型的なリンクは不要
箇条書き形式にする
"""
"要約"="内容に対する要約をMECEに挙げる"

["メール"]
content = """
${content}
"""

