["指示"]
prompt="""
あるニュースレターを読んで、その内容を要約し、考察を行い、関連情報を抽出する仕事を受けました。
[記事本文]から[制約]に沿って[処理]を実行し、[output_format]の形式で[処理]の結果を出力してください。
"""
output_format="""
## \\# 要約

このニュースレターは、最新の技術トレンドや業界の動向についての情報を提供しています。
特に、AI技術の進化やデジタルトランスフォーメーションの重要性が強調されています。

## \\# リンク

- [記事タイトル1](リンク1のURLに括弧をつける)
    - 説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける 
    - 説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける 
- [記事タイトル2](リンク2のURLに括弧をつける)
    - 説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける 
    - 説明文や価格などがある時は要旨を140文字以内でまとめてリンクの後ろにつける 
- [記事タイトル3](リンク3のURLに括弧をつける)

## \\# 考察

ここまでの技術革新は、企業の競争力を大きく左右する要因となっている。
"""

["制約"]
"出力言語"="日本語"
"出力形式"="Markdown形式（コードブロックは使用しない）"
"見出し文字"="##"
"文体"="常体"
"箇条書き"="構造化インデントは4スペース、数字箇条書きは使用せず空改行を入れない"

["処理"]
"要約"="このメールの概要を140字以内で出力"
"リンク"="""
htmlからタイトルとリンクを抽出
ニュース、記事、話題、商品、書名等のリンクをMECEで出力
抽出したリンクのタイトルとURL文字列は改変せず、特にexample.com のようなドメインにはしない
`[タイトル](URL)` の Markdown 形式で必ず括弧を閉じる
リンクの付近に関連する解説や価格などがある場合は4文字スペースのインデントをして箇条書きで付与
数字箇条書きは使用せず、階層箇条書きにする
配信停止、情報配信サービス設定変更、プライバシーポリシー、質問フォーム、お問い合わせなど定型的なリンクは不要
"""
"考察"="メール内の文章やリンクから導出される共通点やトレンドを考察して1000文字程度で出力"

["メール"]
content = """
${content}
"""

