[指示]
[記事情報]と[本文]から[制約]に沿って[処理]を実行し、[処理]の結果を出力
処理の内容

[制約]
文字数制限="2000文字以内"
出力形式="Markdown形式"
見出し文字="##"
文体="常体"

[処理]
主張="記事情報と本文の主張したい内容を140字以内で簡潔に出力"
要約="記事情報と本文の内容を箇条書きで出力"
考察="記事情報と本文から演繹的に導出される考察や新しい視点をステップバイステップで出力"
反論と改善="記事情報と本文に対する反論と、それに対する改善案をステップバイステップで出力"
類似例="記事情報と本文と類似例があれば出力"
ネクストアクション="記事情報と本文から導出される次にすべきことや関連して調べるべき内容を出力"
