"指示"="""
Youtubeの[書き起こし文]から[制約]に沿って[処理]を実行し、[処理]の結果を出力
処理の内容
"""

["制約"]
"出力形式"="Markdown形式"
"見出し文字"="##"
"文体"="常体"

["処理"]
"主張"="記事本文の主張したい内容を140字以内で簡潔に出力"
"要約"="記事本文の記載内容をもれなく箇条書きで出力"
"引用"="記事本文内から有用かつ一般論でない文章を引用符で囲って複数出力"
"考察"="記事本文から問いかけを行い、仮説、示唆、結論としてステップバイステップに熟考して出力"
"SNSシェア用感想"="記事本文から感じたことや考えたことを100字以内で出力し、URLも併記し`で囲む"
"関連"="記事本文から関連情報へのリンクを名前とURLで抽出"
"キーワード"="後から検索できるように本文の重要なキーワードをカンマ区切りで出力"

"書き起こし文"="""
${youtube_transcript}
"""