[指示]
Youtubeの[書き起こし文]から[制約]に沿って[処理]を実行し、[処理]の結果を出力
処理の内容

[制約]
出力形式="Markdown形式"
見出し文字="##"
文体="常体"

[処理]
主張="記事情報と本文の主張したい内容を140字以内で簡潔に出力"
要約="本文の記載内容をもれなく箇条書きで出力"
引用="本文内から特に有用な文章３つを引用符で囲って出力"
考察="記事情報と本文から演繹的に導出される考察や新しい視点をステップバイステップで出力"

[書き起こし文]
${youtube_transcript}