name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Check formatting
        run: black --check --diff .
