name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy Cloud Function
        env:
          FUNCTION_NAME: ${{ secrets.FUNCTION_NAME }}
          TRIGGER_TOPIC: ${{ secrets.TRIGGER_TOPIC }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          SECRETS_MANAGER: ${{ secrets.SECRETS_MANAGER }}
        run: |
          bash deploy.sh
