name: Deploy

on:
    workflow_run:
        workflows: ['Test']
        branches: ['main']
        types:
            - completed
    workflow_dispatch:

jobs:
    deploy:
        if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r src/requirements.txt

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v1
              with:
                  project_id: ${{ secrets.GCP_PROJECT_ID }}
                  service_account_key: ${{ secrets.GCP_SA_KEY }}
                  export_default_credentials: true

            - name: Deploy Cloud Function
              env:
                  FUNCTION_NAME: ${{ secrets.FUNCTION_NAME }}
                  TRIGGER_TOPIC: ${{ secrets.TRIGGER_TOPIC }}
                  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
                  SECRETS_MANAGER: ${{ secrets.SECRETS_MANAGER }}
              run: |
                  gcloud -q functions deploy "$FUNCTION_NAME" \
                    --gen2 \
                    --region=asia-northeast1 \
                    --runtime=python312 \
                    --trigger-topic="$TRIGGER_TOPIC" \
                    --timeout=120s \
                    --min-instances=0 \
                    --max-instances=30 \
                    --memory=512Mi \
                    --source=src/ \
                    --entry-point=main \
                    --service-account "$SERVICE_ACCOUNT" \
                    --set-secrets SECRETS="$SECRETS_MANAGER"
