name: Test

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'
                  cache: 'pip'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r src/requirements.txt

            - name: Create secrets file
              run: |
                  if [ -n '${{ secrets.SECRETS_JSON }}' ]; then
                    echo '${{ secrets.SECRETS_JSON }}' > secrets.json
                  fi

            - name: Create GCS bucket config
              run: |
                  if [ -n '${{ secrets.GCS_BUCKET_JSON }}' ]; then
                    mkdir -p src/conf
                    echo '${{ secrets.GCS_BUCKET_JSON }}' > src/conf/gcs_bucket.json
                  fi

            - name: Run tests
              run: pytest
