name: Test

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'
                  cache: 'pip'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r src/requirements.txt

            - name: Set env for secrets
              run: echo "SECRETS_JSON=${{ secrets.SECRETS_JSON }}" >> $GITHUB_ENV

            - name: Create secrets file
              run: |
                  if [ -n "${{ secrets.SECRETS_JSON }}" ]; then
                    echo "${{ secrets.SECRETS_JSON }}" > secrets.json
                  fi

            - name: Run tests
              run: pytest
