name: Test

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Create secrets file
        if: ${{ secrets.SECRETS_JSON != '' }}
        run: echo '${{ secrets.SECRETS_JSON }}' > secrets.json

      - name: Run tests
        run: pytest
